version: '3'

services:
  web:
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - ./www:/var/www/
  
  database:
    hostname: database
    env_file:
      - ./database.env
    image: mysql
    volumes:
      - ./database:/var/lib/mysql
    restart: always
